name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        working-directory: /var/www/nik19ta.next

    steps:
      - run: git pull
      - run: npm i
      - run: rm -f .env
      - run: cp .env.prod .env
      - run: npm run build
        env:
            CI: true

      - run: pm2 restart nik19ta.next
      # - run: pm2 restart nik19ta.next-back-end
