name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux, X64]
    defaults:
      run:
        working-directory: /var/www/nik19ta.next

    steps:
      - run: git pull
      - run: npm i
      # Build front-end
      - run: npm run build
      # Build back-end
      - run: make build
        env:
            CI: true

      - run: pm2 restart "nik19ta.next"
      - run: pm2 restart "back-end nik19ta's site"
